apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: NodeApp-Demo-Cluster
  region: eu-west-1

vpc:
  id: vpc-e8945f91
  cidr: "172.31.0.0/16"
  subnets:
    public:
      eu-west-1a:
        id: subnet-362d397e
      eu-west-1b:
        id: subnet-79652323
    private:
      eu-west-1a:
        id: subnet-099ee36c5c13bb2b8
      eu-west-1b:
        id: subnet-0745e9aadd8a7dcc9

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.small
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.small
    desiredCapacity: 1
    privateNetworking: true
